# Generated by Django 2.1.4 on 2018-12-20 15:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ApplyController', '0001_initial'),
        ('ManagementController', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponPurchase',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('BuyTime', models.DateTimeField(auto_now_add=True)),
                ('CouponID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementController.Coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderTime', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=500)),
                ('ThumbUpCount', models.PositiveIntegerField()),
                ('ReviewTime', models.DateTimeField(auto_now_add=True)),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyController.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('Sex', models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')])),
                ('PhoneNum', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='^\\d{7}$')])),
                ('Favorite', models.ManyToManyField(to='ApplyController.Restaurant')),
                ('UserRecommend', models.ManyToManyField(to='ManagementController.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('OrderID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UserController.Order')),
                ('Amount', models.PositiveSmallIntegerField()),
                ('DishID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementController.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserController.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='RestaurantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyController.Restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserController.User'),
        ),
        migrations.AddField(
            model_name='couponpurchase',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserController.User'),
        ),
    ]
