# Generated by Django 2.1.4 on 2018-12-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserController', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='RestaurantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyController.Restaurant'),
        ),
    ]
