# Generated by Django 2.1.3 on 2018-12-23 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserController', '0002_auto_20181222_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Score',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='RestaurantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyController.Restaurant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='PhoneNum',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='^\\d{7}$')]),
        ),
    ]
