# Generated by Django 2.1.4 on 2019-01-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyController', '0002_auto_20181226_0216'),
        ('UserController', '0002_auto_20181224_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableNum', models.PositiveSmallIntegerField()),
                ('OccupationDate', models.DateTimeField()),
                ('OccupationTime', models.PositiveSmallIntegerField(choices=[(0, '中饭'), (1, '晚饭')])),
                ('ReserveTime', models.DateTimeField(auto_now_add=True)),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyController.Restaurant')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserController.User')),
            ],
        ),
    ]
