# Generated by Django 2.1.4 on 2018-12-23 16:07

import ManagementController.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ApplyController', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Value', models.FloatField()),
                ('Amount', models.PositiveIntegerField()),
                ('Notes', models.CharField(max_length=200)),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyController.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Image', models.ImageField(null=True, upload_to=ManagementController.models.get_file_path)),
                ('Type', models.PositiveSmallIntegerField(choices=[(0, '开胃菜'), (1, '蔬菜'), (2, '肉类'), (3, '海鲜类'), (4, '汤'), (5, '甜品'), (6, '饮料'), (7, '其他')])),
                ('RecommendCount', models.PositiveIntegerField(default=0)),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyController.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableNum', models.PositiveSmallIntegerField()),
                ('Role', models.PositiveSmallIntegerField(choices=[(0, '商家'), (1, '用户')])),
                ('OccupationDate', models.DateTimeField(auto_now=True)),
                ('OccupationTime', models.PositiveSmallIntegerField(choices=[(0, '中饭'), (1, '晚饭'), (2, '其他')])),
                ('MerchantID_or_UserID', models.CharField(max_length=50)),
                ('ReserveTime', models.DateTimeField(auto_now_add=True)),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyController.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableNum', models.PositiveSmallIntegerField()),
                ('Capacity', models.PositiveSmallIntegerField()),
                ('CloseTime', models.DateTimeField(null=True)),
                ('OpenTime', models.DateTimeField(auto_now=True)),
                ('Status', models.PositiveSmallIntegerField(choices=[(0, '开放'), (1, '待关闭'), (2, '待关闭/开放'), (3, '关闭'), (4, '待开放')], default=0)),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyController.Restaurant')),
            ],
        ),
    ]
