# Generated by Django 2.1.4 on 2018-12-25 18:16

import ManagementController.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementController', '0004_auto_20181225_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=ManagementController.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='OccupationDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='OpenTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 18, 16, 4, 43876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='table',
            name='Status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '开放'), (1, '待关闭'), (2, '待关闭/开放'), (3, '关闭'), (4, '待开放')], null=True),
        ),
    ]
