# Generated by Django 2.1.4 on 2019-01-01 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementController', '0006_auto_20181231_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='RestaurantID',
        ),
        migrations.AlterField(
            model_name='table',
            name='OpenTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 5, 57, 36, 863372, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
