# Generated by Django 2.1.3 on 2018-12-22 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyController', '0001_initial'),
        ('assesses', '0002_assess_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Result', models.PositiveIntegerField(choices=[(0, '通过'), (1, '拒绝')])),
                ('AssessTime', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=18)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Assess',
        ),
        migrations.AddField(
            model_name='assessinfo',
            name='AssessorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesses.Assessor'),
        ),
        migrations.AddField(
            model_name='assessinfo',
            name='RestaurantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyController.Restaurant'),
        ),
    ]
