# Generated by Django 2.1.4 on 2018-12-25 18:16

import ApplyController.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyController', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=ApplyController.models.get_file_path),
        ),
    ]
