# Generated by Django 2.1.3 on 2018-12-23 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyController', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='PhoneNum',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='LicenseID',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')]),
        ),
    ]
